var words = [{
	 word:"envy",
     meaning:"desire to have a quality, possession, or other desirable thing belonging to (someone else).",
     synonym:"Jealousy",
     antonym:"Generosity"},
     {word:"solitude",
     meaning:"the state or situation of being alone.",
     synonym:"Loneliness",
     antonym:"Company"},
	 {word:"autonomous",
     meaning:"Autonomous means self governing",
     synonym:"Self Governing",
     antonym:"Subservient"},
	 {word:"edict",
     meaning:"Edict is a pronouncement,order or decree.",
     synonym:"Order",
     antonym:"Entreaty"},
	 {word:"equitable",
     meaning:"Equitable means to be just or fair in one's own decisions.",
     synonym:"Fair",
     antonym:"Inequitable"},
	 {word:"infirm",
     meaning:"An infirm person is weak and unwell.",
     synonym:"Weak",
     antonym:"Strong"},
	 {word:"confluence",
     meaning:"Confluence means a convergence or an amalgamation.",
     synonym:"Amalgamation",
     antonym:"Divergence"},
	 {word:"Revoke",
     meaning:"To revoke is to take back or withdraw.",
     synonym:"Withdraw",
     antonym:"Evoke"},
	 {word:"quadriga",
     meaning:"A Quadriga is a two-wheeled chariot drawn by four horses abreast.",
     synonym:"Chariot",
     },
	 {word:"idiomorphic",
     meaning:"Idiomorphic means to occur naturally in the form of well developed,distinct crystals.",
     synonym:"Distinct",
     antonym:"Not Distinct"},
	 {word:"regress",
     meaning:"To regress means to relapse or to go back.",
     synonym:"Back",
     antonym:"Advance"},
	 {word:"polychromatic",
     meaning:"Polychromatic means to have a variety of colours.",
     synonym:"Kaleidoscopic",
     antonym:"Monochromatic"},
	 {word:"nettle",
     meaning:"Nettle means to annoy or upset",
     synonym:"Irritate",
     antonym:"Please"},
	 {word:"subordinate",
     meaning:"Having not so great importance or rank as another.",
     synonym:"Junior",
     antonym:"Honcho"},
	 {word:"belligerent",
     meaning:"feeling or displaying eagerness to fight.",
     synonym:"Aggressive",
     antonym:"Affable"},
	 {word:"mellifluous",
     meaning:"Mellifluous means to be sweet sounding.",
     synonym:"Harmony",
     antonym:"Dissonant"},
	 {word:"abject",
     meaning:"Abject means hopeless and downtrodden.",
     synonym:"Hopeless",
     antonym:"Exalted"},
	 {word:"equable",
     meaning:"Equable means steady.",
     synonym:"Steady",
     antonym:"Vacillating"},
     	 
];